### ISSUE TITLE
[FEATURE] How to know the index of the current element being written in an assembly

### ISSUE THREAD

**Issue by blegaut** [RosaeNLG/rosaenlg#102]
**Is your feature request related to a problem? Please describe.**
I have a set of n items, and I am using eachz to describe them. I would like to be able to create several sentences of 3 items max.

**Describe the solution you'd like**
Could we have a way to know the index of the current element being written in an assembly and to use this index as a condition in a separator mixin ?

**Describe alternatives you've considered**
Split my set and add an additonal loop outside the assembly

**Additional context**

**Comment by ludans** [comment]
Hello @blegaut 

There are some generic mechanisms that were originally intended to allow this.
Can you please check: https://rosaenlg.org/rosaenlg/3.0.3/mixins_ref/eachz_itemz.html#_advanced_assemble_dynamically

The important thing is to be able to know programmatically how many elements are non empty and to decide how to assemble depending on this.
But there might be missing mechanisms.

Can you please make some tests?

PS: if you manage making it, I would be happy to enrich the documentation with your example.

**Comment by blegaut** [comment]
I found an hacky way by using an "external" index that get increase each time an item is written.
- recordValue('ASM_INDEX', getValue('ASM_INDEX')+1) 

I can then read the index within the separator mixin, and modify the separator consequently.

This works well since the index get incremented only when a new item is written (not with an empty item)

I believe a much cleaner solution would be the assembly to pass its internal index of the assembly within the params to the separator mixins

**Comment by ludans** [comment]
Can you please post a full example with code?
I'm not 100% sure of the problem to solve.

**Comment by blegaut** [comment]
Here is a code sample to illustrate waht I want to do

```
mixin getAsm(params)
  if getValue('INDEX')==3
    | . Also I like
  else
    | ,
    
- recordValue('INDEX',0);
- let fruits = ['apples', 'bananas', 'pears', 'nuts','pears',' ananas'];
p
  eachz fruit in fruits with {mode:'single_sentence', begin_with_general: 'I like', separator: getAsm}
    - recordValue('INDEX', getValue('INDEX') +1)
    if fruit != 'bananas'
      | #[+value(fruit)]
```

This produces: 
`<p>I like apples, pears, nuts. Also I like pears, ananas</p>`

What would be convenient is to be able to access the eachz index internal value, instead of creating an outside INDEX.
Maybe someting like

```
 mixin getAsm(params)
  if params && params.currentElement &&  params.currentElement .index==3
    | . Also I like
  else
    | ,
```

I hope that this is clearer

**Comment by ludans** [comment]
Let's go back to you initial request:
**I have a set of n items, and I am using eachz to describe them. I would like to be able to create several sentences of 3 items max.**

I don't think there is an easy and immediate way of doing it. 
What you would need is a two step enumeration:
1. sentence level
2. inside a sentence level

e.g.:
```
- var data = ['apples', 'bananas', 'apricots', 'pears', 'ananas'];
p
  eachz fruit in data with { mode: 'sentences', separator: '.', last_separator: 'and', begin_with_general: ['I love', 'I also like'], end:'.', split:3, and: {mode:'single_sentence', separator: ',', last_separator: 'and'} }
    | #{fruit}

I love apples, bananas and apricots. I also like pears and ananas.
```

**Is that what you need?**

Below are all other infructuate options I explored. You may ignore it.


---

When using `... with {assembly: asmFct}`:

`asmFct` will be called with 2 parameters:
1. the length of the non empty list
2. the list itself of the non empty elements

It will be called **only once**: when the non empty list is known, just before generating the text.
Therefore with this mechanism you cannot change the assembly during generation.

---

Assembly cannot have an impact on which elements are generated or not. When evaluating non empty elements, assembly is ignored.

Inside the `itemz`, you can know which elements are empty or not, using `listInfo.nonEmpty`.
But you must not use it to trigger which elements are generated, otherwise it will make empty prediction fail.

```
itemz {mode:'single_sentence', separator: ',', last_separator: 'and'}
  item
    | first
  item
    if WITH_2
      | second
  item
    | third
    //- console.log(listInfo); null first, and has content after
    if listInfo!=null && listInfo.nonEmpty
      | #{JSON.stringify(listInfo)}
```

---

There is a way to know where you are in the enumeration.

```
itemz {mode:'single_sentence', separator: ',', last_separator: 'and'}
  item
    | #{pos}
    | first
  item
    if false
      | second
      | #{pos}
  item
    | #{pos}
    | third
```

which will output `0 first and 2 third`.

But:
- it is not what you need
- you should not use it

**Comment by blegaut** [comment]
Thank you Ludan

The solution you proposed resolves my issue. This is great

I would like to clarify some doubts regarding the other infructuate options.

When you say: 

> Assembly cannot have an impact on which elements are generated or not. When evaluating non empty elements, assembly is ignored.

I understand the point about not making empty prediction fail.
As a general practice, do you see any inconvenient about slightly modifying the content of one item based on a synonym that comes from the assembly ? For instance, if within the assembly, I store a key/value about the use or not of a preposition or a determiner, and read this key when writing the items.

When you say:

> There is a way to know where you are in the enumeration. 
> But:
> 
> - it is not what you need
> - you should not use it> 

Is there an inconvenient to use a condition such as `if pos > 1 then` to add an adverb such as "aussi" in the middle of an item text ?

**Comment by ludans** [comment]
Yes, you can change the content using `pos`, as long as it does change the non empty character of the item.
I am happy that it solved your issue.

I still think that more sophisticated assemblies like I proposed can be useful. I opened #109 , I might work on it someday.
