### ISSUE TITLE
[BUG] `english-verb-helper` imports extraneous dependencies.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [RosaeNLG/rosaenlg#131]
**Describe the bug**
`english-verb-helper` [imports types from `english-verbs-gerunds` and `english-verbs-irregular`](https://github.com/RosaeNLG/rosaenlg/blob/92e3d7b950a5f57987ea132f0ff1aa323c9b72f8/packages/english-verbs-helper/lib/index.ts#L37-L38), but does not list those packages as dependencies (it does list them as devDependencies).

**To Reproduce**
1. Import `mergeVerbsData` from `english-verb-helper` in a TypeScript project that does not also require `english-verbs-gerunds` and `english-verbs-irregular`.
2. Pass unworkable values for the arguments.  There will be no error as the types of those arguments, `EnglishGerunds` and `EnglishVerbsIrregular`, cannot be found.

**Expected behavior**
`english-verb-helper` should have `english-verbs-gerunds` and `english-verbs-irregular` as dependencies, or redeclare the types from those packages.

**Code**

**Context:**
 - RosaeNLG version: N/A
 - Language: N/A
 - Packaging: Node.js

**Additional context**

**Comment by ludans** [comment]
Thanks @wtgtybhertgeghgtwtg 
These resources are not declared as dependencies so that they are not automatically bundled in a browser package (in a browser package, often, you may wish to only include verbs that are really used in your project).
I decided to redeclare the types from those packages.

Can you please check the PR #132 and tell me if it looks ok?

**Comment by wtgtybhertgeghgtwtg** [comment]
I copied it to my local version and it works here.  Thank you for the quick fix.
