### ISSUE TITLE
question application rosaenlgs

### ISSUE THREAD

**Issue by houssem3107** [RosaeNLG/rosaenlg#71]
Hello ,
 I have a question about a rosaenlg application.
I have structured data about a social network( number of persons, number of messages, ...) in an excel file divised into coloumns.
For instance all what i can do is to generate a text that describes what happens in one line of data.

What i want to do is to compare the data between the lines.( For example, the number of persons has increased or the number of messages has decreased compared to the last line)

Is it possible to do so with rosaenlg and if yes how ?
Thanks

**Comment by ludans** [comment]
Hello Houssem,

A real world NLG app works in 2 steps:
1. based on your data, define _what you want to you_, what is the story
2. transform it into text

The **first step** is generally implemented using some simple stats, data crunching etc. Use JavaScript, Python or whatever.
When you mention comparing lines, this must typically be done in the first step.
The output of this first step is still data (not text). It is the technical representation of your story.

The **second step** consists of transforming that story into text (data-to-text). This is done using RosaeNLG templates.
The output is the final text.

It is important to distinguish these two steps, otherwise your second step (RosaeNLG templates) will be messy.

An implementation option is to implement step 1 using JavaScript, in RosaeNLG.
Your RosaeNLG template will:
- get the raw data
- run step 1 using plain JavaScript
- run step 2 using templates

See https://rosaenlg.org/rosaenlg/2.1.9/mixins_ref/otherAndHelpers.html#_include

**Comment by ludans** [comment]
@houssem3107 please tell me if it is clear enough. If so, I'll close the issue.

**Comment by houssem3107** [comment]
Hello,

Thank you for the fast response, it was clear enough
