### ISSUE TITLE
[BUG] Referring Expressions don't work inside the rosaenlg-browser-poc.

### ISSUE THREAD

**Issue by jhofstede** [RosaeNLG/rosaenlg#76]
**Describe the bug**
Referring Expressions don't work inside the rosaenlg-browser-poc.

**To Reproduce**
1. Copy and Paste the Referring Expression Example in one of the `fruits.pug` files
2. Run `npm run build`
3. Open generated html file in the browser
4. The console says `Uncaught InvalidArgumentError: {} has no ref mixin`

**Expected behavior**
To output `<p>The ring / it / it / this jewel</p>`

**Code**
```
- var PRODUCT = {};
mixin PRODUCT_ref(obj, params)
  | the ring
- PRODUCT.ref = PRODUCT_ref;

mixin PRODUCT_refexpr(obj, params)
  synz
    syn
      | this jewel
    syn
      | it
- PRODUCT.refexpr = PRODUCT_refexpr
p #[+value(PRODUCT)]  / #[+value(PRODUCT)] / #[+value(PRODUCT)] / #[+value(PRODUCT)]
```

**Context:**
 - RosaeNLG version: [1.13.0]
 - Language: [ en_US]
 - Packaging: [ browser ]

**Comment by ludans** [comment]
Thanks Julien.

On **version 3.0.0** it actually works with the code you provided, following exactly your steps, see screenshot:
![image](https://user-images.githubusercontent.com/20767031/119162232-6e94ca80-ba5a-11eb-95bd-49a516558a50.png)

If you really want to keep version 1.13.0, see code below with '' around the expression references.
This should work (though I did not test it).

```
- var PRODUCT = {};
mixin PRODUCT_ref(obj, params)
  | the ring
- PRODUCT.ref = 'PRODUCT_ref';

mixin PRODUCT_refexpr(obj, params)
  synz
    syn
      | this jewel
    syn
      | it
- PRODUCT.refexpr = 'PRODUCT_refexpr'
p #[+value(PRODUCT)]  / #[+value(PRODUCT)] / #[+value(PRODUCT)] / #[+value(PRODUCT)]

```

**Comment by jhofstede** [comment]
Ah! Thanks for the quick reply! I figured how I got to use 1.13. Since there wasn't a link to the browser-poc repository, I googled it, ending up using the archived repo at gitlab. So I wasn't using 1.13 by conscious choice. Maybe it's worth to directly link to the correct repository from the documentation.

Two points of feedback:
1. `gulp` is not mentioned as a dependency, I had to install it locally. Maybe it's worth adding it as a devDependency for convenience.
2. `gulpfile.js` points to `../rosaenlg/dist/rollup/....` which doesn't exist from the scope of the package. I changed that to `node_modules` and then it works! 🎉 
```
  - return src([`../rosaenlg/dist/rollup/rosaenlg_tiny_*_${rosaeNlgVersion}.js`]).pipe(dest('dist/'));
  + return src([`node_modules/rosaenlg/dist/rollup/rosaenlg_tiny_*_${rosaeNlgVersion}.js`]).pipe(dest('dist/'));
```

Thanks for the great package!

**Comment by ludans** [comment]
Thanks for your feedback :)

1/
As you mentioned the archived repo on Gitlab (https://gitlab.com/rosaenlg-projects/rosaenlg-browser-poc) is deprecated: the POC is now part of the main mono repo here https://github.com/RosaeNLG/rosaenlg/tree/master/packages/rosaenlg-browser-poc. I have cleared the doc in the old repo:

![image](https://user-images.githubusercontent.com/20767031/119238891-b3496000-bb45-11eb-94c3-fdb3d15a968c.png)

2/
Gulp was not mentioned as a dependency because it is a project-wide dev dependency, declared in https://github.com/RosaeNLG/rosaenlg/blob/master/package.json.
Still I have just added it, as someone could use this package independently of the whole mono repo (and it is not a problem when using the mono repo).

3/
The `../rosaenlg/dist/rollup/....` is meaningful when using the mono repo as it points to the last local compiled package. In this context (which is my dev environment) your suggested path will not work.
Still I ended up putting both https://github.com/RosaeNLG/rosaenlg/pull/77/files#diff-8b32128fb1f96c4e49c0a55fbdf67875925a565b9d96fc6260bcf0edfed36cd9.

You may check https://github.com/RosaeNLG/rosaenlg/tree/master/packages/rosaenlg-browser-poc and tell if it works properly on your setup.
