### ISSUE TITLE
[OTHER] Croatian support

### ISSUE THREAD

**Issue by dddominikk** [RosaeNLG/rosaenlg#86]
Been meaning to do this for about a year now, ever since first discovering this project, but I'm finally comfortable enough with both JavaScript and Pug to discuss the possibility of contributing without googling stuff every five seconds lol.

I've just read the contribution guidelines and so, based on that and everything else I've learned about RosaeNLG so far, I believe I'll be able to facilitate Croatian support either primarily or exclusively through lists.  The language is morphologically similar to French in the sense that the only difference between its grammar rules and exceptions to the same is that there are usually n cases in which you apply a rule and n-1 cases in which you apply an exception. 😅

I'm filling the language specification form right now and have one question regarding it: there's a query asking about whether "stop words" exist in a given target language. But that term is a SEO construct more so than a linguistic one, as far as I know. Meaning stop words exist in pretty much every language, no?

Oh, one notable difference between French and Croatian is in the number of cases - three versus seven. Should I even worry about such peculiarities at this stage?

I might also be able to help with some additional beginner-friendly templates but I'll open a separate topic for that one once I've filtered through my existing templates. I've spent the last dozen or so years writing and editing for a living so combined with my  ever-growing js skillset, I'm hoping I'll be able to accomplish this without too much in the way of outside help. No idea on the ETA, though.

**Comment by ludans** [comment]
Hi

**Comment by ludans** [comment]
Hi @dddominikk

I would be happy to help you contributing on Croatian.

The language specification helps a lot to give a good overview of the job to be done.

Once this is done, I can definitely have a look and check complexity.
Implementation guide is https://github.com/RosaeNLG/rosaenlg/blob/master/DEVELOPER_GUIDE.md#add-a-new-language. Implementation can be done step by step: typically, verbs are generally not so important at the beginning because in many NLG applications, it's ok to have them static in the templates.

When managing exceptions, rules and/or explicit exception lists are the key - but knowing the language is the most important.

For stopwords, it is quite standard and largely available in many languages. What about using https://www.npmjs.com/package/stopwords-hr? I use stopwords-fr for French, stopwords-it for Italian, etc. Stopwords list are used only in the synonyms optimization module of RosaeNLG.

Let's start documenting cases in NEW_LANGUAGE.md file for Croatian. We'll check together how/when it would be relevant to implement it. Cases are usually quite a pain (for German, they bring complexity and increase the size of the linguistic resources).

Having a sample template in Croatian, typically the translated tutorial, or something like https://rosaenlg.org/rosaenlg/3.0.0/tutorials/example_en_US.html, is very useful.
When implementing, we will write quantity of templates as test cases.

**Comment by dddominikk** [comment]
>When managing exceptions, rules and/or explicit exception lists are the key - but knowing the language is the most important.

Thank you for the swift response, I guess I overthinked stopwords.

I'm hoping accuracy won't be a concern as I'm a native speaker. Will report back once I have something concrete, cheers.

**Comment by ludans** [comment]
hello @dddominikk 
are you still willing to work on this topic?
